COMPANY_NAME = "google"
VACANCY_NAME = "project manager"
EMAIL = "google_recruitment@google.com"
VACANCY_RESPONSIBILITIES = [
    "plan",
    "develop",
    "lead",
]
# VOC1 METRIC PARAMS
VOC1_PLUS_UNIQUE_PROPORTION = 0.4

# VOC2 METRIC PARAMS
VOC2_MINUS_ORTH_THRESHOLD = 2
VOC2_MINUS_COLL_PROPORTION = 0.2
VOC2_PLUS_ORTH_THRESHOLD = 0
VOC2_PLUS_COLL_PROPORTION = 0.05
